spring.application.name=mailproject
# ===============================
# SERVER AYARLARI
# ===============================
server.port=8080

# ===============================
# RABBITMQ BA?LANTI AYARLARI
# ===============================
# Az nce kurdu?umuz lokal RabbitMQ bilgileri
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Retry Mekanizması
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=5000ms

# ===============================
# MAILTRAP (SMTP) AYARLARI
# ===============================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=BURAYA_MAILTRAP_KULLANICI_ADIN_GELECEK
spring.mail.password=BURAYA_MAILTRAP_SIFREN_GELECEK
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true